name: Run problem
description: When helper doesnt start and its obviously not a bug in the helper
labels: [run problem]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a run problem report, please search for the behaviour in the existing issues. 
        
        ---
  
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use?"
      options:
        - Windows 7
        - Windows 8
        - Windows 10
        - Windows 11
        - Other windows version. (please specify in the description!)
    validations:
      required: true 
  - type: dropdown
    id: systemlang
    attributes:
      label: Systemlanguage
      description: "Which system language do you use?"
      options:
        - German (DE)
        - English (EN)
        - Russian (RU)
        - Other windows language. (please specify in the description!)
    validations:
      required: true 
  - type: input
    id: gameversion
    attributes:
      label: Current Game-Version
      description: "Please provide the current game version you use."
      placeholder: "5.30.0"
    validations:
      required: true
  - type: input
    id: helperversion
    attributes:
      label: RSL Helper Version
      description: "Please provide your current used helper version."
      placeholder: "v3.1.5.54"
    validations:
      required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: Please describe what happens and why the helper seems to not start.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we may need to take to reproduce this behavior?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
